### PR TITLE
issue 91

### PR DESCRIPTION
**Pull request by xactant**
Updated `Moralis Web3 Unity SDK` to `Web3GameKit` and updated README.md

### CODE REVIEW

**Comment by GilbertoBitt** [comment]
this fixed the transaction problem about "
Transaction decoding is not available for chainId 97"?

**Review by KoenRijpstra — APPROVED** [review]
LGTM!

**Review by KoenRijpstra — CHANGES_REQUESTED** [review]
The `MoralisServerSettings.asset` file should stay in the `Assets/Moralis Web3 Unity SDK/Resources/` folder and not be moved to the new `Web3GameKit` folder.

**Review by KoenRijpstra — CHANGES_REQUESTED** [review]
I see that the guid in the `Assets/Moralis Web3 Unity SDK.meta` file changed. Can you revert that just to be safe? And then it is good to go 👍

**Pull request merged**
